### ISSUE TITLE
appengine:deploy fails

### ISSUE THREAD

**Issue by phaas** [google/software-product-sprint#35]
After much bisecting to find the common path between a working app and the portfolio app, the issue appears to be the cache config in `appengine-web.xml`:

```
 <static-files>
    <!-- prevent unwanted caching when accessing via the web preview server -->
    <include path="/**" expiration="0" />
  </static-files>
```

This configuration causes the GAE tooling to generate this application description, which results in a `HTTP/500` error when initiation the new version flow:

```
application: 'gae-simple-test-2'
runtime: java8
version: '1'
inbound_services:
- warmup
derived_file_type:
- java_precompiled
auto_id_policy: default
api_version: 'user_defined'
handlers:
- url: (/.*/)
  static_files: __static__\1index.html
  upload: __NOT_USED__
  require_matching_file: True
  login: optional
  secure: optional
  expiration: 0
- url: (/)
  static_files: __static__\1index.html
  upload: __NOT_USED__
  require_matching_file: True
  login: optional
  secure: optional
  expiration: 0
- url: (/.*)
  static_files: __static__\1
  upload: __NOT_USED__
  require_matching_file: True
  login: optional
  secure: optional
  expiration: 0
- url: /
  script: unused
  login: optional
  secure: optional
- url: /.*/
  script: unused
  login: optional
  secure: optional
- url: /_ah/.*
  script: unused
  login: optional
  secure: optional
- url: /data
  script: unused
  login: optional
  secure: optional
```
